language: generic
services:
- docker

before_install:
  - docker build -t rm01964/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rm01964/react-test npm test



after_success:
  - docker build -t rm01964/multi-client ./client
  - docker build -t rm01964/multi-nginx ./nginx
  - docker build -t rm01964/multi-server ./server
  - docker build -t rm01964/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  # this shall help with rapid container distribution
  - docker push rm01964/multi-client
  - docker push rm01964/multi-nginx
  - docker push rm01964/multi-server
  - docker push rm01964/multi-worker

  deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-745232509913
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY

