language: generic
services:
- docker

before_install:
  - docker build -t rpenunuri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rpenunuri/react-test npm test

after_success:
  - docker build -t rpenunuri/multi-client ./client
  - docker build -t rpenunuri/multi-nginx ./nginx
  - docker build -t rpenunuri/multi-server ./server
  - docker build -t rpenunuri/multi-worker ./worker

  # Log in to the docker CLI
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # Take those images and push them to docker hub
  - docker push rpenunuri/multi-client
  - docker push rpenunuri/multi-nginx
  - docker push rpenunuri/multi-server
  - docker push rpenunuri/multi-worker
